name: Build and Release Electron App

on:
  push:
    tags:
      - 'v-*'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install
        
      - name: Install TypeScript
        run: yarn global add typescript

      - name: Build/release Electron app
        uses: paneron/action-electron-builder@v1.8.1
        with:
            build_script_name: build:win
            github_token: ${{ secrets.GH_TOKEN }}
            release: ${{ startsWith(github.ref, 'refs/tags/v-') }}