name: Build and Release Electron App

on:
  push:
    tags:
      - 'v-*'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        
      - name: Install TypeScript
        run: npm install -g typescript
        
      # - name: Build/release Electron app
      #   uses: paneron/action-electron-builder@v1.8.1
      #   with:
      #       build_script_name: build:win
      #       github_token: ${{ secrets.GH_TOKEN }}
      #       release: ${{ startsWith(github.ref, 'refs/tags/v-') }}

      - name: Build Electron app
        run: npm build:win

      - name: Release Electron app
        uses: ncipollo/release-action@v1.14.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag: ${{ github.ref_name }}
          artifacts: './dist/*.exe'
          generateReleaseNotes: true